options:
    city1: 서울

on load:
    broadcast "&9 전쟁 스크립트 리로드"

command /test <integer>:
    trigger:
        conquer(arg-1)

function conquer(a: integer, b: integer):

    set {_arm} to ArmSend({_a})
    set {_city} to CitySend({_b})
    if {_a} is 1:
        set {_arm} to "남한군"
    else:
        set {_arm} to "북한군"

    broadcast "{@city1}이 %{_arm}%에 의해 점령되었습니다!"

function ArmSend(n : integer):
    return {city::{_n}}

on step on iron block:
    